Checking CI for packer status check

diff --git a/.github/workflows/packer-status-check.yaml b/.github/workflows/packer-status-check.yaml
--- a/.github/workflows/packer-status-check.yaml
+++ b/.github/workflows/packer-status-check.yaml
@@ -3,15 +3,23 @@ name: Packer Status Check
 on:
   pull_request:
     branches:
-      - main  # Change to your default branch if it's not 'main'
+      - main
 
 jobs:
-  fmt:
+  packer-check:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0  # This ensures all history is fetched
+
+      - name: Create repository archive
+        run: |
+          zip -r webapp.zip . -x '*.git*'
+          mkdir -p packer
+          mv webapp.zip packer/
 
       - name: Run Packer Init
         run: |
@@ -20,10 +28,14 @@ jobs:
 
       - name: Run Packer Format Check
         run: |
-          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer hashicorp/packer:latest fmt -check test.pkr.hcl
-
+          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer \
+          hashicorp/packer:latest fmt -check test.pkr.hcl || { echo "Packer format check failed"; exit 1; }
 
       - name: Run Packer Validate
+        env:
+          MY_APP_SERVICE_CONTENT: ${{ secrets.MY_APP_SERVICE_CONTENT }}
         run: |
           docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer \
-          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest validate test.pkr.hcl || { echo "Packer validate failed"; exit 1; }
+          -e MY_APP_SERVICE_CONTENT \
+          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest validate \
+          -var "my_app_service_content=$MY_APP_SERVICE_CONTENT" test.pkr.hcl || { echo "Packer validate failed"; exit 1; }
