Checking CI for packer status check

diff --git a/.github/workflows/packer-status-check.yaml b/.github/workflows/packer-status-check.yaml
--- a/.github/workflows/packer-status-check.yaml
+++ b/.github/workflows/packer-status-check.yaml
@@ -17,7 +17,8 @@ jobs:
 
       - name: Create webapp.zip
         run: |
-          zip -r webapp.zip . -x ".git" "packer-template/" ".github/"
+          mkdir -p packer-template
+          zip -r webapp.zip . -x ".git/*" "packer-template/*" ".github/*"
           mv webapp.zip packer-template/
 
       - name: List repository contents
@@ -39,6 +40,7 @@ jobs:
           done
 
       - name: Upload webapp.zip as artifact
+        if: ${{ success() }}
         uses: actions/upload-artifact@v3
         with:
           name: webapp-artifact
@@ -46,24 +48,26 @@ jobs:
 
       - name: Run Packer Init
         run: |
-          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer-template \
-          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest init test.pkr.hcl || { echo "Packer init failed"; exit 1; }
+          docker run --rm -v "${{ github.workspace }}:/workspace" \
+            -w /workspace/packer-template -v packer_plugins:/root/.config/packer/plugins \
+            hashicorp/packer:latest init test.pkr.hcl || { echo "Packer init failed"; exit 1; }
 
       - name: Run Packer Format Check
         run: |
-          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer-template \
-          hashicorp/packer:latest fmt -check test.pkr.hcl || { echo "Packer format check failed"; exit 1; }
+          docker run --rm -v "${{ github.workspace }}:/workspace" \
+            -w /workspace/packer-template hashicorp/packer:latest fmt -check test.pkr.hcl \
+            || { echo "Packer format check failed"; exit 1; }
 
       - name: Run Packer Validate
         env:
           MY_APP_SERVICE_CONTENT: ${{ secrets.MY_APP_SERVICE_CONTENT }}
-          DB_PASSWORD: ${{ secrets.Password }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           DB_NAME: ${{ secrets.DB_NAME }}
         run: |
-          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer-template \
-          -e MY_APP_SERVICE_CONTENT -e Password -e DB_NAME \
-          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest validate \
-          -var "MY_APP_SERVICE_CONTENT=${MY_APP_SERVICE_CONTENT}" \
-          -var "Password=${Password}" \
-          -var "DB_NAME=${DB_NAME}" \
-          test.pkr.hcl || { echo "Packer validate failed"; exit 1; }
+          docker run --rm -v "${{ github.workspace }}:/workspace" \
+            -w /workspace/packer-template -e MY_APP_SERVICE_CONTENT -e DB_PASSWORD -e DB_NAME \
+            -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest validate \
+            -var "MY_APP_SERVICE_CONTENT=${MY_APP_SERVICE_CONTENT}" \
+            -var "Password=${DB_PASSWORD}" \
+            -var "DB_NAME=${DB_NAME}" \
+            test.pkr.hcl || { echo "Packer validate failed"; exit 1; }
