Updated packer build

diff --git a/.github/workflows/packer-build.yaml b/.github/workflows/packer-build.yaml
--- a/.github/workflows/packer-build.yaml
+++ b/.github/workflows/packer-build.yaml
@@ -78,3 +78,104 @@ jobs:
           cd packer-template
           packer build -debug -var-file=variables.pkrvars.hcl \
             test.pkr.hcl
+          
+      #Set up the AWS ACCOUNT
+      - name: SET UP AWS CLI 
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+            aws-access-key-id: ${{ secrets.AWS_DEMO_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.AWS_DEMO_SECRET_KEY_ID }}
+            aws-region: us-east-1
+
+      #List files after aws cli setup
+      - name: List the files after the setup
+        run: |
+          ls -l #list files to verify setup is correct or not
+
+      - name: Install jq
+        run: sudo apt-get install -y jq
+
+      #check packer manifest and set AMI ID from manifest
+      - name: Checking packer manifest and set AMI ID from manifest
+        run: |
+            cd packer #naviagte to the packer directory
+            cat manifest.json #Display the content of the packer manifest file
+            AMI_ID=$(jq -r '.builds[-1].artifact_id | split(":") | .[1]' manifest.json)
+            echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV #Set the AMI_ID as env variables
+            echo "AMI_ID set to: $AMI_ID" #Verify that the value is correctly set
+
+      #Verify AMI_ID before moving ahead
+      - name: Verify AMI_ID is correctly set
+        run: |
+            echo "Verifying AMI_ID: ${{ env.AMI_ID }}"
+            if [[ -z "${{ env.AMI_ID }}" ]]; then
+              echo "AMI ID is not correctly set. Exiting."
+              exit 1
+            fi
+        
+      # Step: Create New Launch Template Version
+      - name: Create New Launch Template Version
+        run: |
+          echo "Using AMI_ID: ${{ env.AMI_ID }}"
+          # Get the latest version of the launch template
+          LATEST_VERSION=$(aws ec2 describe-launch-templates \
+            --launch-template-name csye6225_asg \
+            --query 'LaunchTemplates[0].LatestVersionNumber' --output text)
+          echo "Cloning from Launch Template Version: $LATEST_VERSION"
+          
+          # Create a new version of the launch template with the updated AMI
+          aws ec2 create-launch-template-version \
+            --launch-template-name csye6225_asg \
+            --source-version "$LATEST_VERSION" \
+            --version-description "New version with latest AMI" \
+            --launch-template-data "{\"ImageId\": \"${{ env.AMI_ID }}\"}"
+          ls -l #Verify directory contents after launch template version create-launch-template-version
+
+
+      - name: Update ASG with latest template version
+        run: |
+            echo "Using AMI_ID: ${{ env.AMI_ID }}"
+            #Fetch the latest version number of the launch template
+            VERSION=$(aws ec2 describe-launch-templates \
+              --launch-template-name csye6225_asg \
+              --query 'LaunchTemplates[0].LatestVersionNumber' --output text)
+            echo "Latest Launch Template Version: $VERSION"
+            aws autoscaling update-auto-scaling-group \
+              --auto-scaling-group-name csye6225-web-app-asg \
+              --launch-template "LaunchTemplateName=csye6225_asg,Version=$VERSION"
+
+
+      - name: Start Instance refresh and monitor
+        run: |
+            REFRESH_ID=$(aws autoscaling start-instance-refresh \
+              --auto-scaling-group-name csye6225-web-app-asg \
+              --query 'InstanceRefreshId' \
+              --output text)
+            echo "Started instance refresh with ID $REFRESH_ID"
+            ls -l #List files to confirm the setup before entering the monitor
+            while true; do
+              STATUS=$(aws autoscaling describe-instance-refreshes \
+                --auto-scaling-group-name csye6225-web-app-asg \
+                --query "InstanceRefreshes[?InstanceRefreshId=='$REFRESH_ID'].Status" \
+                --output text)
+
+              echo "Current refresh status: $STATUS"
+              if [[ "$STATUS" == "Successful" ]]; then
+                echo "Instance refresh completed successfully."
+                exit 0
+              elif [[ "$STATUS" == "Failed" || "$STATUS" == "Cancelled" ]]; then
+                echo "Instance refresh failed or was Cancelled"
+                exit 1
+              else
+                echo "Instance refresh in progress. Checking again in 30 seconds..."
+                sleep 30
+              fi
+            done 
+
+
+              
+            
+
+      
+          
+      
