Checking workflow

diff --git a/.github/workflows/packer-status-check.yaml b/.github/workflows/packer-status-check.yaml
--- a/.github/workflows/packer-status-check.yaml
+++ b/.github/workflows/packer-status-check.yaml
@@ -19,10 +19,10 @@ jobs:
 
       - name: Run Packer Init
         run: |
-          # Run packer init to install missing plugins
-          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer hashicorp/packer:latest init test.pkr.hcl || { echo "Packer init failed"; exit 1; }
+          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer \
+          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest init test.pkr.hcl || { echo "Packer init failed"; exit 1; }
 
       - name: Run Packer Validate
         run: |
-          # Validate the Packer template
-          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer hashicorp/packer:latest validate test.pkr.hcl || { echo "Packer validate failed"; exit 1; }
+          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace/packer \
+          -v packer_plugins:/root/.config/packer/plugins hashicorp/packer:latest validate test.pkr.hcl || { echo "Packer validate failed"; exit 1; }
